name: PR Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches-ignore:
      - 'rc/**'
      - 'main'

jobs:
  action:
    uses: AlaskaAirlines/auro-actions/.github/workflows/pull-request.yml@main
    with:
      demo-dir: './auro-formkit-demo'
      demo-build-command: 'npm run local-demo'
      cache-dirs: |
        ./components/**/dist
        ./components/**/demo
        ./components/**/node_modules
        ./node_modules
        ./custom-elements.json
    secrets:
      NPM_TOKEN: $\{{ secrets.NPM_TOKEN }}